# Site settings
title: From a wanderer's perspective
email: gurupratap91@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  I write here to share my perspective of things. 
baseurl: "" # the subpath of your site, e.g. /blog/
#url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: gurupratap91	
github_username:  gurupratap91

# Build settings
markdown: kramdown
